backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: img/

collections:
  - name: "session"
    label: "Session"
    folder: "src/session"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "contentKey"
        widget: "hidden"
        default: "session"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Level"
        name: "level"
        widget: "number"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pageData/index.md"
        label: "Index Page"
        name: "index-page"
        fields:
          - name: "contentKey"
            widget: "hidden"
            default: "indexPage"
          - label: "Tagline"
            name: "tagline"
            widget: "string"
          - label: "Hero Image"
            name: "Hero Image"
            widget: "image"


